version: 2.1
name: Trigger CircleCi job

on:
  push:
      branches:
        - master

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Check ls"
          command: ls

      - run:
          name: "Install kubernetes"
          command: |
            set -x
            curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.0/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl

      - run:
          name: "Check kubectl version"
          command: kubectl version --client
          
