version: 2.1
name: Trigger CircleCi job


on:
  push:
      branches:
        - master

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Check ls"
          command: ls
      - run:
          name: "Make kubectl work"
          command: |
            set -x
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
            echo "$(<kubectl.sha256) kubectl" | sha256sum --check
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl version --client
            chmod +x kubectl
            mkdir -p ~/.local/bin/kubectl
            mv ./kubectl ~/.local/bin/kubectl
            ls -art  ~/.local/bin/kubectl

#      - run:
#          name: "Deploy Flask API and MYSQL database with kubectl"
#          command: |
#            set -x
#            sudo kubectl apply -f mysql-pv.yml
#            kubectl apply -f mysql-deployment.yml
#            kubectl apply -f flaskapp-deployment.yml
          
