version: 2.1
name: Trigger CircleCi job

on:
  push:
      branches:
        - master

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Check ls"
          command: ls